name: O Meu Robo de Vagas

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  atualizar-site:
    runs-on: ubuntu-24.04
    steps:
      - name: Puxar os ficheiros
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Navegador Fantasma
        run: |
          pip install playwright bs4 requests
          playwright install chromium
          playwright install-deps

      - name: Correr o script scraper.py
        run: python scraper.py

      - name: Guardar as alterações no site
        run: |
          git config --global user.name "Robo Trabalhador"
          git config --global user.email "robo@vagas.pt"
          git add vagas.json
          git commit -m "Robô: Vagas de Portugal atualizadas" || echo "Sem novas vagas"
          git push
